### ISSUE TITLE
Local Python Script Installation Help

### ISSUE THREAD

**Issue by wwjd1234** [uchidalab/time_series_augmentation#1]
The docs say i need to install:

    pip install tensorflow-gpu==2.4.1 keras==2.2.4 numpy==1.19.5 matplotlib==2.2.2 
    scikit-image==0.15.0 tqdm

But when running the jupyter notebook everything runs fine without having to install anything. Thus, if I want to move the code to a python script how would I use:

    import utils.augmentation as aug

Do I need to install a library or copy over this code to my project?
I do not need to run this on a GPU.

Is the only file I need to generate augmented data?: 

    augmentation.py

If only using that file then the only thing I would need to install would be the following;

    pip install tqdm

**Comment by biwana** [comment]
The requirements are to run the full example and the code in the papers. Sorry about the miscommunication.

Yes, if all you care about is the augmentation, then all you need is numpy, tqdm, and augmentation.py. 
You don't even need tqdm, that is just used to print out the progress, it can be removed.
