### ISSUE TITLE
Format of the input

### ISSUE THREAD

**Issue by jeiglsperger** [uchidalab/time_series_augmentation#2]
Hi!

Great work with Discriminative Guided Warping, I want to it out by myself with some of my own datasets but I'm not quite sure about the format of the input. In the docs, it says it should be in the format `(batch, time_steps, channel)`.
In the case of my dataset, which is a table with sales data over multiple years with let's say 1000 samples (days) and 10 features/channels (like sales of certain products, weekday, date, etc.). So I would have to split this dataset into sequences with the sequence length `time_steps` and `batch` would be the number of sequences I have after splitting, am I right? `Channel` would still be the number of features, of course.

Kind regards!

**Comment by biwana** [comment]
The format you are talking about comes from keras. 
In keras, `batch_size` is the size of a subset of data used in one forward iteration. It's normally a set number that is much smaller than your dataset (32 to 128 is normal).
`time_steps`, for your case, would be days
`channel`, for your case would be the 10 features

"batch" has a different meaning in the utils/augmentation.py file, but that doesn't have anything to do with the input shape.

**Comment by jeiglsperger** [comment]
Ok great, thank you!

**Comment by jeiglsperger** [comment]
But when I look at the Jupyter Notebook example with the CBF dataset, the format is the following:
```
print(x_train.shape)
hlp.plot1d(x_train[0], aug.discriminative_guided_warp(x_train, y_train)[0])
```
`(30, 128, 1)`
and that would correspond to the format (number_of_samples, number_of_features, number_of_dimensions), when I read the raw dataset correctly.

**Comment by biwana** [comment]
Sorry, I was confused because of the word "batch". Yes, the `x_train `is the whole dataset, not just a batch. So, your example will be `(XXX, 1000, 10)` where `XXX `is the number of samples in your dataset. In my example, I use the same input shape as you would in `model.fit() `in keras. 

So, to use it, you could do something like 

```
% load data
x_train = np.genfromtxt("traindata.csv")
y_train = np.genfromtxt("trainlabels.csv")

% add jittering
augmentation = aug.jitter(x_train)
x_augment_train = np.append(x_train, augmentation, axis=0)

% duplicate the labels to match the augmentation
y_augment_train = np.append(y_train, y_train, axis=0)

% train model
model = ...
model.compile()
model.fit(x_augment_train, y_augment_train)
```

**Comment by jeiglsperger** [comment]
Ah ok, now I understand better, but in my example, it would be `(1000, 10, 1)` when I understand it right, as the `number_of_samples = 1000` (1000 days), the  `number_of_features = 10` and `number_of_dimensions = 1`.
